version: "3.8"

services:
    app:
        build: .
        command: sh -c "python main.py"
        # Replace "YOUR_USER" for your Docker Hub user
        image: kapoork31/face_mask_rec:latest
        ports:
            - "80:8000"